name: it_planner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  # Обновите до последней
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1  # Обновите!
  json_annotation: ^4.8.1
  image_picker: ^1.0.6  # Обновите!
  file_picker: ^10.3.7 
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1
  flutter_dotenv: ^5.1.0
  open_file: ^3.3.3
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
